# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fort < Formula
  desc "One command. Every Mac. SOC 2 ready."
  homepage "https://github.com/djadmin/fort"
  version "0.2.0"
  license "MIT"
  depends_on :macos

  url "https://github.com/djadmin/fort/releases/download/v0.2.0/fort_darwin_all.tar.gz"
  sha256 "50499df08530f93021d4ca17200faf9ec4dfc0e7f2dd437fd46408c0f544294d"

  define_method(:install) do
    bin.install "fort"
  end

  test do
    system "#{bin}/fort", "--version"
  end
end
