# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fort < Formula
  desc "One command. Every Mac. SOC 2 ready."
  homepage "https://github.com/djadmin/fort"
  version "0.3.1"
  license "MIT"
  depends_on :macos

  url "https://github.com/djadmin/fort/releases/download/v0.3.1/fort_darwin_all.tar.gz"
  sha256 "b0abd1276182b2e555d759ae9f0d2a84691e6345fce9b156b8dcd8c0ba3e3ede"

  define_method(:install) do
    bin.install "fort"
  end

  test do
    system "#{bin}/fort", "--version"
  end
end
